[general]
output = "example"
primfn = "default_primary_classification"
pidfn = "default_pid"
fsthresh = [
    "@photon_threshold",
    "@electron_threshold",
    "@muon_threshold",
    "@pion_threshold",
    "@proton_threshold",
]

[parameters]
photon_threshold = 25.0
electron_threshold = 70.0
muon_threshold = 25
pion_threshold = 25.0
proton_threshold = 40.0

[[category]] # 0 : Neutrino, charged current 1e1p
cuts = [
    { name = "neutrino" },
    { name = "fiducial_cut"},
    { name = "nonelectron_containment_cut"},
    { name = "no_photons", parameters = [ "@photon_threshold"   ]},
    { name = "single_electron", parameters = [ "@electron_threshold"   ]},
    { name = "no_charged_pions", parameters = [ "@pion_threshold"   ]},
    { name = "no_muons", parameters = [ "@muon_threshold"   ]},
    { name = "single_proton", parameters = [ "@proton_threshold"   ]},
]
[[category]] # 1 : Neutrino, charged current 1eNp (N > 1)
cuts = [
    { name = "neutrino" },
    { name = "fiducial_cut"},
    { name = "nonelectron_containment_cut"},
    { name = "no_photons", parameters = [ "@photon_threshold"   ]},
    { name = "single_electron", parameters = [ "@electron_threshold"   ]},
    { name = "no_charged_pions", parameters = [ "@pion_threshold"   ]},
    { name = "no_muons", parameters = [ "@muon_threshold"   ]},
    { name = "multiproton", parameters = [ "@proton_threshold"   ]},
]
[[category]] # 2 : Neutrino, Uncontained and Out of Fiducial Volume (OOFV)
cuts = [
    { name = "neutrino" },
    { name = "no_photons", parameters = [ "@photon_threshold"   ]},
    { name = "single_electron", parameters = [ "@electron_threshold"   ]},
    { name = "no_charged_pions", parameters = [ "@pion_threshold"   ]},
    { name = "no_muons", parameters = [ "@muon_threshold"   ]},
    { name = "multiproton", parameters = [ "@proton_threshold"   ]},
]
[[category]] # 3 : Neutrino, Other CC Nue
cuts = [
    { name = "neutrino" },
    { name = "iscc"    },
    { name = "single_electron", parameters = [ "@electron_threshold"   ]},
]

[[category]] # 4 : Neutrino, Other CC Numu
cuts = [
    { name = "neutrino" },
    { name = "iscc"    },
    { name = "single_muon", parameters = [ "@muon_threshold"   ]},
]

[[category]] # 5 : Neutrino, neutral current
cuts = [
    { name = "neutrino" },
    { name = "!iscc"    },
]

[[category]] # 6 : Cosmic
cuts = [
    { name = "!neutrino" },
]
[[category]] # 7 : Neutrino, Other
cuts = [
    { name = "neutrino" },
]

[[sample]]
name = "simulation"
path = "/pnfs/icarus/persistent/users/dcarber/spine/combined_files/NuMI_CV_flat_cafs_2/*.root"
ismc = true

[[sample]]
name = "cvext"
path = "/pnfs/icarus/persistent/users/dcarber/spine/combined_files/NuMI_Nue_det_sys_flat_cafs/NuMI_nue_det_CV.root"
ismc = true
disable = false

[[sample]]
name = "var00"
path = "/pnfs/icarus/persistent/users/dcarber/spine/combined_files/NuMI_Nue_det_sys_flat_cafs/NuMI_nue_det_Null_Sample.root"
ismc = true
disable = false

[[sample]]
name = "var01p"
path = "/pnfs/icarus/persistent/users/dcarber/spine/combined_files/NuMI_Nue_det_sys_flat_cafs/NuMI_nue_det_GainHigh.root"
ismc = true
disable = false

[[sample]]
name = "var01m"
path = "/pnfs/icarus/persistent/users/dcarber/spine/combined_files/NuMI_Nue_det_sys_flat_cafs/NuMI_nue_det_GainLow.root"
ismc = true
disable = false

[[sample]]
name = "var02p"
path = "/pnfs/icarus/persistent/users/dcarber/spine/combined_files/NuMI_Nue_det_sys_flat_cafs/NuMI_nue_det_High_Coh.root"
ismc = true
disable = false

[[sample]]
name = "var03p"
path = "/pnfs/icarus/persistent/users/dcarber/spine/combined_files/NuMI_Nue_det_sys_flat_cafs/NuMI_nue_det_High_Int.root"
ismc = true
disable = false

[[sample]]
name = "var04p"
path = "/pnfs/icarus/persistent/users/dcarber/spine/combined_files/NuMI_Nue_det_sys_flat_cafs/NuMI_nue_det_High_Life.root"
ismc = true
disable = false

[[sample]]
name = "var02m"
path = "/pnfs/icarus/persistent/users/dcarber/spine/combined_files/NuMI_Nue_det_sys_flat_cafs/NuMI_nue_det_Low_Coh.root"
ismc = true
disable = false

[[sample]]
name = "var03m"
path = "/pnfs/icarus/persistent/users/dcarber/spine/combined_files/NuMI_Nue_det_sys_flat_cafs/NuMI_nue_det_Low_Int.root"
ismc = true
disable = false

[[sample]]
name = "var04m"
path = "/pnfs/icarus/persistent/users/dcarber/spine/combined_files/NuMI_Nue_det_sys_flat_cafs/NuMI_nue_det_Low_Life.root"
ismc = true
disable = false

[[sample]]
name = "var05"
path = "/pnfs/icarus/persistent/users/dcarber/spine/combined_files/NuMI_Nue_det_sys_flat_cafs/NuMI_nue_det_Scint_Var.root"
ismc = true
disable = false

[[sample]]
name = "var06"
path = "/pnfs/icarus/persistent/users/dcarber/spine/combined_files/NuMI_Nue_det_sys_flat_cafs/NuMI_nue_det_Wire_gap.root"
ismc = true
disable = false

[[sample]]
name = "var07"
path = "/pnfs/icarus/persistent/users/dcarber/spine/combined_files/NuMI_nu_det_YZ_unif*.root"
ismc = true
disable = false

[[tree]]
name = "selected_1e1p"
sim_only = false
mode = "reco"
cut = [
    { name = "fiducial_cut",     type = "reco" },
    { name = "nonelectron_containment_cut",  type = "reco" }, #This cut isn't in the default medulla. Look at ...
    { name = "flash_cut", type = "reco", parameters = [0,9.6]},
    { name = "no_photons",       type = "reco", parameters = [ "@photon_threshold"   ] },
    { name = "single_electron",     type = "reco", parameters = [ "@electron_threshold" ] },
    { name = "no_charged_pions", type = "reco", parameters = [ "@pion_threshold"     ] },
    { name = "no_muons",      type = "reco", parameters = [ "@muon_threshold"     ] },
    { name = "single_proton",    type = "reco", parameters = [ "@proton_threshold"   ] },
]
branch = [
    {name = "neutrino_id",            type = "true"},
    {name = "cc",                    type = "mctruth"},
    {name = "pdg",                   type = "mctruth"}, #Needed for NuMI Flux calculation
    {name = "parent_pdg",            type = "mctruth"}, #Needed for NuMI Flux calculation
    {name = "interaction_type",      type = "mctruth"},
    {name = "neutrino_energy",       type = "mctruth"}, #Needed for NuMI Flux calculation
    {name = "category",              type = "true"},
    {name = "visible_energy",        type = "both"},
    {name = "fiducial",              type = "reco"},
    {name = "containment",           type = "reco"},
    {name = "flash_time",            type = "reco"},
    {name = "photon_multiplicity",   type = "reco", parameters = [ "@photon_threshold"   ]},
    {name = "electron_multiplicity", type = "reco", parameters = [ "@electron_threshold" ]},
    {name = "muon_multiplicity",     type = "reco", parameters = [ "@muon_threshold"     ]},
    {name = "pion_multiplicity",     type = "reco", parameters = [ "@pion_threshold"     ]},
    {name = "proton_multiplicity",   type = "reco", parameters = [ "@proton_threshold"   ]},
    {name = "ke",                    type = "both_particle", selector = "leading_electron"   },
    {name = "start_dedx",            type = "reco_particle", selector = "leading_electron"   },
    {name = "start_straightness",    type = "reco_particle", selector = "leading_electron"   },
    {name = "axial_spread",          type = "reco_particle", selector = "leading_electron"   },
    {name = "directional_spread",    type = "reco_particle", selector = "leading_electron"   },
    {name = "vertex_distance",       type = "reco_particle", selector = "leading_electron"   },
    {name = "muon_softmax",          type = "reco_particle", selector = "leading_proton" },
    {name = "pion_softmax",          type = "reco_particle", selector = "leading_proton" },
    {name = "proton_softmax",        type = "reco_particle", selector = "leading_proton" },
]
[[tree]]
name = "selected_1eNp"
sim_only = false
mode = "reco"
cut = [
    { name = "fiducial_cut",     type = "reco" },
    { name = "nonelectron_containment_cut",  type = "reco" }, #This cut isn't in the default medulla. Look at ...
    { name = "flash_cut", type = "reco", parameters = [0,9.6]},
    { name = "no_photons",       type = "reco", parameters = [ "@photon_threshold"   ] },
    { name = "single_electron",     type = "reco", parameters = [ "@electron_threshold" ] },
    { name = "no_charged_pions", type = "reco", parameters = [ "@pion_threshold"     ] },
    { name = "no_muons",      type = "reco", parameters = [ "@muon_threshold"     ] },
    { name = "multiproton",    type = "reco", parameters = [ "@proton_threshold"   ] },
]
branch = [
    {name = "neutrino_id",            type = "true"},
    {name = "cc",                    type = "mctruth"},
    {name = "pdg",                   type = "mctruth"}, #Needed for NuMI Flux calculation
    {name = "parent_pdg",            type = "mctruth"}, #Needed for NuMI Flux calculation
    {name = "interaction_type",      type = "mctruth"},
    {name = "neutrino_energy",       type = "mctruth"}, #Needed for NuMI Flux calculation
    {name = "category",              type = "true"},
    {name = "visible_energy",        type = "both"},
    {name = "fiducial",              type = "reco"},
    {name = "containment",           type = "reco"},
    {name = "flash_time",            type = "reco"},
    {name = "photon_multiplicity",   type = "reco", parameters = [ "@photon_threshold"   ]},
    {name = "electron_multiplicity", type = "reco", parameters = [ "@electron_threshold" ]},
    {name = "muon_multiplicity",     type = "reco", parameters = [ "@muon_threshold"     ]},
    {name = "pion_multiplicity",     type = "reco", parameters = [ "@pion_threshold"     ]},
    {name = "proton_multiplicity",   type = "reco", parameters = [ "@proton_threshold"   ]},
    {name = "ke",                    type = "both_particle", selector = "leading_electron"   },
    {name = "start_dedx",            type = "reco_particle", selector = "leading_electron"   },
    {name = "start_straightness",    type = "reco_particle", selector = "leading_electron"   },
    {name = "axial_spread",          type = "reco_particle", selector = "leading_electron"   },
    {name = "directional_spread",    type = "reco_particle", selector = "leading_electron"   },
    {name = "vertex_distance",       type = "reco_particle", selector = "leading_electron"   },
    {name = "muon_softmax",          type = "reco_particle", selector = "leading_proton" },
    {name = "pion_softmax",          type = "reco_particle", selector = "leading_proton" },
    {name = "proton_softmax",        type = "reco_particle", selector = "leading_proton" },
]

[[tree]] #This tree is needed if you want to calculate the efficiency
name = "signal_1e1p"
sim_only = true
mode = "true"
cut = [
        { name = "fiducial_cut",     type = "true" },
    { name = "nonelectron_containment_cut",  type = "true" },
    { name = "no_photons",       type = "true", parameters = [ "@photon_threshold"   ] },
    { name = "single_electron",     type = "true", parameters = [ "@electron_threshold" ] },
    { name = "no_charged_pions", type = "true", parameters = [ "@pion_threshold"     ] },
    { name = "no_muons",      type = "true", parameters = [ "@muon_threshold"     ] },
    { name = "single_proton",    type = "true", parameters = [ "@proton_threshold"   ] },
]

branch = [
    {name = "neutrino_id",            type = "true"},
    {name = "cc",                    type = "mctruth"},
    {name = "pdg",                   type = "mctruth"}, #Needed for NuMI Flux calculation
    {name = "parent_pdg",            type = "mctruth"}, #Needed for NuMI Flux calculation
    {name = "interaction_type",      type = "mctruth"},
    {name = "neutrino_energy",       type = "mctruth"}, #Needed for NuMI Flux calculation
    {name = "category",              type = "true"},
    {name = "visible_energy",        type = "both"},
    {name = "fiducial",              type = "reco"},
    {name = "containment",           type = "reco"},
    {name = "flash_time",            type = "reco"},
    {name = "photon_multiplicity",   type = "reco", parameters = [ "@photon_threshold"   ]},
    {name = "electron_multiplicity", type = "reco", parameters = [ "@electron_threshold" ]},
    {name = "muon_multiplicity",     type = "reco", parameters = [ "@muon_threshold"     ]},
    {name = "pion_multiplicity",     type = "reco", parameters = [ "@pion_threshold"     ]},
    {name = "proton_multiplicity",   type = "reco", parameters = [ "@proton_threshold"   ]},
    {name = "ke",                    type = "both_particle", selector = "leading_electron"   },
    {name = "start_dedx",            type = "reco_particle", selector = "leading_electron"   },
    {name = "start_straightness",    type = "reco_particle", selector = "leading_electron"   },
    {name = "axial_spread",          type = "reco_particle", selector = "leading_electron"   },
    {name = "directional_spread",    type = "reco_particle", selector = "leading_electron"   },
    {name = "vertex_distance",       type = "reco_particle", selector = "leading_electron"   },
    {name = "muon_softmax",          type = "reco_particle", selector = "leading_proton" },
    {name = "pion_softmax",          type = "reco_particle", selector = "leading_proton" },
    {name = "proton_softmax",        type = "reco_particle", selector = "leading_proton" },
[[tree]] #This tree is needed if you want to calculate the efficiency
name = "signal_1eNp"
sim_only = true
mode = "true"
cut = [
        { name = "fiducial_cut",     type = "true" },
    { name = "nonelectron_containment_cut",  type = "true" },
    { name = "no_photons",       type = "true", parameters = [ "@photon_threshold"   ] },
    { name = "single_electron",     type = "true", parameters = [ "@electron_threshold" ] },
    { name = "no_charged_pions", type = "true", parameters = [ "@pion_threshold"     ] },
    { name = "no_muons",      type = "true", parameters = [ "@muon_threshold"     ] },
    { name = "multiproton",    type = "true", parameters = [ "@proton_threshold"   ] },
]

branch = [
    {name = "neutrino_id",            type = "true"},
    {name = "cc",                    type = "mctruth"},
    {name = "pdg",                   type = "mctruth"}, #Needed for NuMI Flux calculation
    {name = "parent_pdg",            type = "mctruth"}, #Needed for NuMI Flux calculation
    {name = "interaction_type",      type = "mctruth"},
    {name = "neutrino_energy",       type = "mctruth"}, #Needed for NuMI Flux calculation
    {name = "category",              type = "true"},
    {name = "visible_energy",        type = "both"},
    {name = "fiducial",              type = "reco"},
    {name = "containment",           type = "reco"},
    {name = "flash_time",            type = "reco"},
    {name = "photon_multiplicity",   type = "reco", parameters = [ "@photon_threshold"   ]},
    {name = "electron_multiplicity", type = "reco", parameters = [ "@electron_threshold" ]},
    {name = "muon_multiplicity",     type = "reco", parameters = [ "@muon_threshold"     ]},
    {name = "pion_multiplicity",     type = "reco", parameters = [ "@pion_threshold"     ]},
    {name = "proton_multiplicity",   type = "reco", parameters = [ "@proton_threshold"   ]},
    {name = "ke",                    type = "both_particle", selector = "leading_electron"   },
    {name = "start_dedx",            type = "reco_particle", selector = "leading_electron"   },
    {name = "start_straightness",    type = "reco_particle", selector = "leading_electron"   },
    {name = "axial_spread",          type = "reco_particle", selector = "leading_electron"   },
    {name = "directional_spread",    type = "reco_particle", selector = "leading_electron"   },
    {name = "vertex_distance",       type = "reco_particle", selector = "leading_electron"   },
    {name = "muon_softmax",          type = "reco_particle", selector = "leading_proton" },
    {name = "pion_softmax",          type = "reco_particle", selector = "leading_proton" },
    {name = "proton_softmax",        type = "reco_particle", selector = "leading_proton" },


